
service: serverless_yolo

frameworkVersion: '3'
useDotenv: true


provider:
  name: aws
  runtime: python3.11
  stage: ${opt:stage, 'dev'}
  region: ${env:AWS_REGION, 'us-east-1'}
  ecr:
    images:
      martech_inference:
        path: ./
        platform: linux/amd64

package:
  patterns:
    - '!venv/**'
    - '!.env*'
    - '!.gitignore'
    - '!.dockerignore'
    - '!node_modules'
    - '!models'
    - '!docker'
    - '!notebooks'


plugins:
  - serverless-prune-plugin

custom:
  prune:
    automatic: true
    includeLayers: true
    number: 2

functions:
  analyseImageCreative:
    handler: src/lambda_function.lambda_handler
    # timeout: 30
    # memorySize: 512
    # image:
    #   name: serverless_yolo
    #   command:
    #     - src/lambda_function.lambda_handler
